setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
setopt EXTENDED_GLOB
setopt NO_FLOW_CONTROL
setopt AUTO_CD
setopt CLOBBER
setopt NO_BEEP
setopt AUTO_PARAM_SLASH
setopt NOTIFY
unsetopt RM_STAR_SILENT
setopt RM_STAR_WAIT

PROMPT_EOL_MARK='%K{red} %k'